package wci.message;

public enum MessageType {

	SOURCE_LINE, SYNTAX_ERROR, PARSER_SUMMARY, INTERRETER_SUMMARY,
	COMPILER_SUMMARY, MISCELLANEOUS, TOKEN, ASSIGN, FETCH, BREAKPOINT,
	RUNTIME_ERROR, CALL, RETURN,
	
}
